### ISSUE TITLE
下载下来安装好之后，页面出现这个怎么办呢

### ISSUE THREAD

**Issue by summeryio** [worldzhao/music-react#1]
Failed to compile
./src/views/dashboard/player/index.jsx
  Line 7:  Casing of ../../rolling/index does not match the underlying filesystem  import/no-unresolved

Search for the keywords to learn more about each error.
This error occurred during the build time and cannot be dismissed.

**Comment by worldzhao** [comment]
不好意思，这是一个奇怪的问题，是由于src/views/Rolling文件夹R大写的原因，可是我的mac上明明是小写，结果推到github一直是大写，还更新不了，我研究一下，同学只用改一下文件夹名字就可以运行了，等我更新成功再拉一次，谢谢关注！
