### ISSUE TITLE
对request.ts封装的疑问？

### ISSUE THREAD

**Issue by ZhangMingZhao1** [worldzhao/music-react#3]
在request.ts全局拦截这里：
```
// 增加响应拦截器
instance.interceptors.response.use(
  response => {
    const { data } = response;
    // 存在业务异常 抛出给业务代码去捕获
    if (data.code !== 200) {
      return Promise.reject(data);
    }
    // 不存在业务异常返回数据
    return data;
  },
  error => {
    // return Promise.reject(error); 非业务异常无需抛出错误 内部吞掉
    const { status } = error.response;
    console.warn(`http error: status-${status} message-${codeMessage[status]}`);
    if(codeMessage[status]!==null||undefined) {
      Toast.info(codeMessage[status]);
    }else {
      Toast.info(error);
    }
    return null;
  }
);
```

说到data.code !== 200时，是属于业务异常，reject，但在你的业务代码中，比如getBanner方法中，没看到用try-catch包住，也没看到.catch接住。所以当返回的数据里面data.code不为200时reject后怎么处理的？

**Comment by worldzhao** [comment]
我的锅，前段时间手机掉了，换了备用机，没登录邮箱，真不好意思。

这方面我也是自己琢磨，没和什么人沟通交流过，可能存在些问题，欢迎互相交流。

业务异常若没接住error，代码中断执行，不会有影响，可能catch住，进行一个toast提示比较好，这里偷懒了，因为一般get请求获取数据很少存在业务异常的场景，索性就没有处理。

但post/patch/put等相关语义的请求，就有必要catch走异常业务分支了。譬如是登录场景，密码错误/用户名错误等等，这个时候就应该catch住，根据错误码进行相应的业务异常流程了。

其实非业务异常，譬如网络错误也应该直接抛出而不是接住吞掉，吞掉返回undefined或者null就要进行很多判空操作，这里也是我最近发现不太对的地方。

晚了一个月才回复，抱歉抱歉，互相学习！
